### ISSUE TITLE
Enhancement, GPS Location on Create Maps section

### ISSUE THREAD

**Issue by Brennan-Walsh** [peterLaurence/TrekMe#52]
I would be great to have the current location displayed in the open streetmaps maps so that one is able to zoom in quickly to an area that they are currently in and then download an offline map.

**Comment by peterLaurence** [comment]
Good idea, will do

**Comment by Brennan-Walsh** [comment]
Thanks. this is working really nicely. It is now quick and easy to find ones location on the map
