### ISSUE TITLE
APK gone?

### ISSUE THREAD

**Issue by IzzySoft** [peterLaurence/TrekMe#56]
Looks like the APK is gone from your repo. Could you please bring it back again (ideally, attached to its corresponding release tag) – for those outside of Play Store? Thanks in advance!

**Comment by peterLaurence** [comment]
This is because this app isn't free (even if the source code is accessible). It wouldn't be fair to all those people that bought the app, to have the apk downloadable for free. It takes me a lot of time to develop this app and support people asking for advice.
Though if you're a developer, nothing prevents you from building it (from the last tagged version) and install it on your device for free.

**Comment by IzzySoft** [comment]
Understood – thanks Peter! As I had made it available [here](https://apt.izzysoft.de/fdroid/index/apk/com.peterlaurence.trekme), do you want me to remove it immediately? I've already added a note that it won't be updated in my repo anymore (will become visible later today, with the next sync in a few hours) – or are you OK with the old version staying there?

**Comment by peterLaurence** [comment]
Indeed, I would appreciate that you remove the old apk, as having people install an old version can cause troubles (if they encounter issues, they won't get any updates).
On the other hand I'm ok with the app referenced on your repo. I should also add it to other stores..

**Comment by IzzySoft** [comment]
I cannot "reference" it from the repo unless it's there – that's how APT repositories work: listing what's inside them. So of course I understand if you want it removed, but then gone is gone. So just let me know what it should be :wink:

Compromise: The note should now be in effect, saying the app will no longer be updated in my repo. Shall we give it a little to sink in, and remove it a bit later? Say, 4…8 weeks from now?

**Comment by peterLaurence** [comment]
If I understand correctly, the site apt.izzysoft.de only contains free apps.
So in that case, it should indeed be removed.

**Comment by IzzySoft** [comment]
OK, done (effective with the next sync tomorrow). A pity, but I understand. Good luck with your app then! Should you wish to have it added back, just let me know: I kept the metadata, so it's easy to re-establish.

**Comment by peterLaurence** [comment]
Thanks. Maybe one day I will reconsider having a lite version of TrekMe which would be free. In that case I will let you know.

**Comment by IzzySoft** [comment]
Great, thanks – looking forward to that! I'll stay subscribed to this issue, so a ping here should reach me.
