### ISSUE TITLE
(Feature request) Support NMEA GPSD over IP

### ISSUE THREAD

**Issue by alectrocute** [peterLaurence/TrekMe#58]
Fantastic work here, @peterLaurence.

This would become the world's best off-road driving app in an instant if this feature were to be added. I'm a little new to Java and NMEA/GPSD in general, but looks like if we deviate from using Android's Location Provider, it could possibly be trivial to create a "GPS from IP server" feature.

**Comment by peterLaurence** [comment]
I will investigate and see the implications on the app overall.

Based on a first quick research, if I understand correctly, you have some hardware that has "NMEA GPS" that you would like TrekMe to listen over WiFi or Bluetooth. Is this correct ?

**Comment by peterLaurence** [comment]
Alright. I'm adding this to my todo list.

**Comment by peterLaurence** [comment]
Do you have any requirement regarding the version of NMEA?
For NMEA 2000, if found [this](https://gpsd.gitlab.io/gpsd/NMEA.html#_gga_global_positioning_system_fix_data).
There's also the former NMEA 0183

**Comment by alectrocute** [comment]
@peterLaurence It would be NMEA 2000.

**Comment by peterLaurence** [comment]
So I've done some research. While the global structure of NMEA sentences is known, how each field should be decoded isn't freely accessible. One has to pay to get the NMEA2000 norm and use it.
I won't spend countless hours reverse engineering some random github project that partially does the job. So I'm afraid it's a dead end.

However, one thing that I could do is expose some simple structure of "gps sentense" that TrekMe would listen over a TCP socket. This way, owners of proprietary protocols could use it, but with a compatibility layer between their protocol and TrekMe.

**Comment by peterLaurence** [comment]
I could add basic support of NMEA 2000 if someone provides me the relevant part of the specification (GPS frames).

**Comment by peterLaurence** [comment]
Done in 2.8.0

**Comment by alectrocute** [comment]
@peterLaurence You're amazing!
