### ISSUE TITLE
Map list does not update correctly after last map is deleted

### ISSUE THREAD

**Issue by Brennan-Walsh** [peterLaurence/TrekMe#59]
When i try to delete the last map in the My Map list, the list does not update. After closing and reopening the App the list then shows up correctly.  

![image](https://user-images.githubusercontent.com/37300817/60501139-cc2f9a80-9cbb-11e9-928a-5fd549e6a6c5.png)

**Comment by peterLaurence** [comment]
This one should be easy to fix. Thanks for reporting.
