### ISSUE TITLE
Free IGN subscription supported?

### ISSUE THREAD

**Issue by Otiel** [peterLaurence/TrekMe#61]
I have a free IGN subscription (annual and limited to 2 000 000 transactions), with a 24-characters key.

Is this supported by TrekMe?

_(I didn't try it, I'd like to make sure it works before buying the app)_

**Comment by peterLaurence** [comment]
Yes it is. The app actually guides you to get one if you don't already have it (and it's free).
What isn't free on the other hand is to download an IGN map for offline usage. I wasn't my decision. IGN enforces that.
Downloading IGN maps for offline usage requires an annual subscription of ~8€. Comparatively to other apps, TrekMe costs less per year (most app require an annual ~15€ subscription for IGN content).

**Comment by peterLaurence** [comment]
But if it's for you own usage - as it seems you're a developer you can easily recompile TrekMe after a little change in the source code so that.. you know..
I don't mind ;)

**Comment by Otiel** [comment]
Thanks for the detailed answer.

I'm curious - when you say "IGN enforces that" - you mean there is no technical constraint?

**Comment by peterLaurence** [comment]
There is no technical constraint. The app requires the user to pay for an annual subscription, just to activate a download button which is deactivated by default.

**Comment by Otiel** [comment]
I see.

Well the online mode is good enough for me to start, will buy the app. 👍 

Thanks for your support.
