### ISSUE TITLE
GPX Recoder not working when Phone is locked

### ISSUE THREAD

**Issue by jules-ch** [peterLaurence/TrekMe#66]
TrekMe Version **2.3.2**
Android **10.0**

The GPX Recorder is only recording position when the app is in the foreground.
I don't know if Android 10 new permission system is preventing the recording.

I get straight lines when recording when I open the app when recording.

<img src="https://user-images.githubusercontent.com/43635101/92176357-91d10880-ee3e-11ea-8e98-65308c7ece6f.jpg" width="400">

**Comment by peterLaurence** [comment]
Nice catch. I should be able to fix that soon.

**Comment by peterLaurence** [comment]
It was indeed an Android 10 issue. Actually, people who had Android 9 and migrated to Android 10 don't have this issue.
The version 2.3.3 is in the release pipeline.

**Comment by jules-ch** [comment]
Awesome it's working great ! :)
