### ISSUE TITLE
Add IGN slopes

### ISSUE THREAD

**Issue by emilevauge** [peterLaurence/TrekMe#72]
Hey!
Great app (fast, simple & effective) 👏 
As a ski touring fan, I would love to have access to [IGN slopes](https://www.geoportail.gouv.fr/actualites/montagne-mieux-prevenir-le-risque-davalanche-avec-la-carte-des-pentes) that help a lot towards avalanches.
Do you think it could be possible to add that layer, on top of the IGN topo map?
Thanks, and kudos for the job done on this 👍

**Comment by peterLaurence** [comment]
That would be an amazing feature, indeed. For now, we can't mix several layers. I can design an interface were we would select a mix of several layers with different opacity.
Then, adding IGN slopes would be easy. I'll definitely work on that.

**Comment by peterLaurence** [comment]
The feature is implemented. It'll be part of the upcoming `2.6.9` version.

**Comment by emilevauge** [comment]
Awesome, you rock!
